### ISSUE TITLE
JSON type is not compatible with mysql db

### ISSUE THREAD

**Issue by MartinMuzatko** [anchan828/typeorm-helpers#513]
I get this error, when I try to set up the type according to the readme.

code:
```
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm'
import { JsonTransformer } from '@anchan828/typeorm-transformers'

class StateJson {
    whatever?: number
}

@Entity()
export default class TriggerLink {

    @PrimaryGeneratedColumn()
    id: number

    @Column({ transformer: new JsonTransformer<StateJson>() })
    triggerState: StateJson
}
```

error:

``` ts
(node:9210) UnhandledPromiseRejectionWarning: DataTypeNotSupportedError: Data type "StateJson" in "TriggerLink.triggerState" is not supported by "mysql" database.
    at new DataTypeNotSupportedError (/home/misan/dev/gitlab/sphinx/src/error/DataTypeNotSupportedError.ts:9:9)
    at /home/misan/dev/gitlab/sphinx/src/metadata-builder/EntityMetadataValidator.ts:87:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/home/misan/dev/gitlab/sphinx/src/metadata-builder/EntityMetadataValidator.ts:84:36)
    at /home/misan/dev/gitlab/sphinx/src/metadata-builder/EntityMetadataValidator.ts:45:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/home/misan/dev/gitlab/sphinx/src/metadata-builder/EntityMetadataValidator.ts:45:25)
    at Connection.buildMetadatas (/home/misan/dev/gitlab/sphinx/src/connection/Connection.ts:527:33)
    at Connection.<anonymous> (/home/misan/dev/gitlab/sphinx/src/connection/Connection.ts:193:18)
    at step (/home/misan/dev/gitlab/sphinx/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
(node:9210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9210) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  
```

**Comment by anchan828** [comment]
Hi @MartinMuzatko 

The column type should be string type (varchar/text/etc.). please add it to Column decorator.

```typescript
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm'
import { JsonTransformer } from '@anchan828/typeorm-transformers'

class StateJson {
    whatever?: number
}

@Entity()
export default class TriggerLink {

    @PrimaryGeneratedColumn()
    id: number

    @Column({ transformer: new JsonTransformer<StateJson>(), type: "text" })
    triggerState: StateJson
}
```

Updated README
https://github.com/anchan828/typeorm-helpers/commit/b46793823897174dbae8a9bceda993a79d9c337d

**Comment by MartinMuzatko** [comment]
aah! I see.
This way it works. Thank you :)

I was able to get a similar setup without the jsontransformer.

``` ts
    @Column('simple-json', { default: '{}' })
    triggerState: {}
```

Looks better documented and elegant with jsontransformer though.
Thanks!
